osx_image: xcode611
language: objective-c
before_install: gem install cocoapods xcpretty obcd -N
cache: cocoapods
podfile: JazzHandsDemo/Podfile
env:
- LC_CTYPE=en_US.UTF-8 LANG=en_US.UTF-8
script:
- set -o pipefail && xcodebuild -workspace JazzHandsDemo/JazzHandsDemo.xcworkspace
  -scheme JazzHandsDemo -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 6" 
  clean test | xcpretty -c
- pod lib lint --quick
- obcd --path src find HeaderStyle
notifications:
  slack:
    secure: VXPjydABzxvSHGDdPPkIdTGtgemahefi++aZM2bMU5/V81/EhjvEHL8XmqEv6g7D/BDULXhl17ylKJ9ilMemk+5GEy5qhTwENkqglGyK9jMQaO5/x4OYLxN/yCTZtGb/73OVUHZtPDg9m1J+gIkzsQF8m2ZVN916u/t4FVL6Vgg=
